/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import gov.hhs.fhh.data.Person;
import gov.hhs.fhh.web.test.AbstractFhhWebTest;

import java.util.Date;
import java.util.GregorianCalendar;

import org.junit.Test;

/**
 * @author bpickeral
 *
 */
public class DateFieldHandlerTest extends AbstractFhhWebTest {
    private final DateFieldHandler handler = new DateFieldHandler();
    private final GregorianCalendar DUMMY_DATE_1 = new GregorianCalendar(2008, 9, 7, 10, 20, 30);
    private final GregorianCalendar DUMMY_DATE_2 = new GregorianCalendar(2008, 9, 7, 0, 0, 0);
    private final String DUMMY_DATE_STR = "10/07/2008";

    @Test
    public void testGetValue() {
        Person p = new Person();
        
        //Make sure that the hour, min, second get truncated (10, 20, 30)
        p.setDateOfBirth(DUMMY_DATE_1.getTime());
        assertEquals(DUMMY_DATE_STR, (String) handler.getValue(p));
        
        p.setDateOfBirth(null);
        assertNull(handler.getValue(p));
    }
    
    @Test
    public void testsetValue() {
        Person p = new Person();
        handler.setValue(p, DUMMY_DATE_STR);
        assertEquals(p.getDateOfBirth(), DUMMY_DATE_2.getTime());
        assertEquals(DUMMY_DATE_STR, (String) handler.getValue(p));
        
        handler.setValue(p, "invalid");
        assertNull(p.getDateOfBirth());
    }
    
    @Test
    public void testNewInstance() {
        assertNull(handler.newInstance(new Object()));
    }
    
    @Test
    public void testResetValue() {
        Person p = new Person();
        p.setDateOfBirth(new Date());
        handler.resetValue(p);
        assertNull(p.getDateOfBirth());
    }
    
    @Test
    public void testCheckValidity() {
        //Depreciated method does nothing.
        handler.checkValidity(new Object());
    }
}
