/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.model.mfhp;

import com.fiveamsolutions.hl7.model.Demographics;
import com.fiveamsolutions.hl7.model.Person;
import com.fiveamsolutions.hl7.model.age.Age;
import com.fiveamsolutions.hl7.model.mfhp.TwinStatus;

/**
 * @author bpickeral
 * @deprecated DO NOT USE THIS CLASS EVER -- STEVE & BRIAN H.
 */
public class RelativeDemographics implements Demographics {
    private String name;
    private LivingStatus livingStatus;
    private Age ageAtDeath;
    private boolean adopted = false;
    private TwinStatus twinStatus;
    private Person person;

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 
     * @return the ageAtDeath
     */
    public Age getAgeAtDeath() {
        return ageAtDeath;
    }

    /**
     * @param ageAtDeath the ageAtDeath to set
     */
    public void setAgeAtDeath(Age ageAtDeath) {
        this.ageAtDeath = ageAtDeath;
    }

    /**
     * @return the livingStatus
     */
    public LivingStatus getLivingStatus() {
        return livingStatus;
    }

    /**
     * @param livingStatus the livingStatus to set
     */
    public void setLivingStatus(LivingStatus livingStatus) {
        this.livingStatus = livingStatus;
    }

    /**
     * @return the adopted
     */
    public boolean isAdopted() {
        return adopted;
    }

    /**
     * @param adopted the adopted to set
     */
    public void setAdopted(boolean adopted) {
        this.adopted = adopted;
    }

    /**
     * @return the twinStatus
     */
    public TwinStatus getTwinStatus() {
        return twinStatus;
    }

    /**
     * @param twinStatus the twinStatus to set
     */
    public void setTwinStatus(TwinStatus twinStatus) {
        this.twinStatus = twinStatus;
    }

    /**
     * @return the person
     */
    public Person getPerson() {
        return person;
    }

    /**
     * @param person the person to set
     */
    public void setPerson(Person person) {
        this.person = person;
    }
}
