/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.test.selenium;

import org.junit.Test;


/**
 * @author kelamin
 * 
 * 
 * 
 *
 */
public class FHHGetHelpTest extends AbstractFHHSeleniumTest {
	
	
	
	
    @Test
    public void testFhhGetHelp() throws Exception {
        openFHH();
        gethelpFH1();
       }
        
  //test the get help forms on Family History entire site
    private void gethelpFH1() throws Exception {
    	selenium.click("link=Get Help");
    	selenium.waitForPopUp("newWin", "30000");
    	selenium.selectWindow("title=My Family Health Portrait");
		waitForText("Create");
//		selenium.click("//div[@id='helpDetail']/div/div[3]/div/a/img");
		selenium.selectWindow("title=My Family Health Portrait - Welcome");
		clickAndWaitForSubmodal("link=Use a Saved History");
		waitForText("Open From Computer");
		Thread.sleep(2000);
		selenium.click("link=Get Help");
		selenium.waitForPopUp("newWin", "30000");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("You will");
        selenium.click("closeHelp");
		selenium.selectWindow("title=My Family Health Portrait - Welcome");
		clickAndWaitForSubmodal("link=Create a Family Health History");
		waitForText("Your Personal Information");
		Thread.sleep(2000);
		selenium.click("xpath=//table[@id='hi-title']/tbody/tr/td[2]/a");
		selenium.waitForPopUp("newWin", "30000");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("When creating");
        selenium.click("closeHelp");
		selenium.selectWindow("title=My Family Health Portrait");
		selenium.click("navHelpUrl");
		selenium.waitForPopUp("newWin", "30000");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("Check");
        selenium.click("closeHelp");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("Create My History");
		selenium.click("navReindex");
		selenium.waitForPageToLoad("48000");
		selenium.click("navHelpUrl");
		selenium.waitForPopUp("newWin", "30000");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("Select");
        selenium.click("closeHelp");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("Copy and Save History");
		selenium.click("navViewDiagram");
		selenium.waitForPageToLoad("48000");
		selenium.click("navHelpUrl");
		selenium.waitForPopUp("newWin", "30000");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("View");
        selenium.click("closeHelp");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("You can print");
		clickAndWaitForSubmodal("link=Diagram & Table Options");
		waitForText("Diagram & Table Options");
		Thread.sleep(2000);
		selenium.click("link=Get Help");
		selenium.waitForPopUp("newWin", "30000");
		selenium.selectWindow("title=My Family Health Portrait");
		waitForText("Choose");
        selenium.click("closeHelp");
		selenium.selectWindow("title=My Family Health Portrait");
    	}
}
