/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.test.selenium;

import gov.hhs.fhh.test.ear.TestProperties;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

import org.junit.Test;

/**
 * Tests is phishing vulnerability exists.
 * @author bpickeral
 */
public class PhishingTest extends AbstractFHHSeleniumTest {
    private final String PHISH_TEXT = "<iframe id=frameshouldnotexist src=http://www.google.com>";


    @Test
    public void testPhishingVulerability() throws Exception {
        try {
            String url = "http://" + TestProperties.getServerHostname() + ":" + TestProperties.getServerPort()
                    + "/fhh-web";
            URL server = new URL(url);
            HttpURLConnection connection = (HttpURLConnection) server.openConnection();
            connection.connect();
        } catch (MalformedURLException e) {
            fail(e.getMessage());
        } catch (IOException e) {
            fail(e.getMessage());
        }
        
        selenium.open("/fhh-web/familyHistory/familyHistory.action?request_locale=es'\">"
                            + PHISH_TEXT + "&amp;maintainState=true'\">" + PHISH_TEXT);
        waitForText("My Family Health History");
        assertFalse(selenium.isElementPresent("frameshouldnotexist"));
    }
}
