/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.data.util;

import gov.hhs.fhh.data.AgeRange;
import gov.hhs.fhh.data.Relative;

/**
 * @author bpickeral
 *
 */
public class RelationshipHolderNode extends Relative {
    private static final long serialVersionUID = 12423342333553L;
    private Relative parentNode;
    
    /**
     * @return the parentNode
     */
    public Relative getParentNode() {
        return parentNode;
    }

    /**
     * @param parentNode the parentNode to set
     */
    public void setParentNode(Relative parentNode) {
        this.parentNode = parentNode;
    }

    /**
     * Default constructor.
     */
    public RelationshipHolderNode() {
        //Default constructor
    }
    
    /**
     * Parameterized constructor.
     * @param relative to set
     */
    public RelationshipHolderNode(Relative relative) {
        super(relative);
    }
    
    /**
     * @return the ageRangeFieldHandler
     */
    public DeceasedEstimatedAgeNode getDeceasedEstimatedAgeNode() {
        DeceasedEstimatedAgeNode node = null;
        AgeRange ageAtDeath = getAgeAtDeath();
        if (ageAtDeath != null) {
            if (ageAtDeath.getOriginalText() != null) {
                node = new DeceasedEstimatedAgeNode(ageAtDeath.getOriginalText());
            } else {
                node = new DeceasedEstimatedAgeNode(ageAtDeath.getUnit(), 
                        ageAtDeath.getLowValue(), ageAtDeath.getHighValue());
            }
        }
        return node;
    }
    
    /**
     * Sets the ageRange based on the AgeRangeHelper passed in.
     * @param daceasedEstimatedAgeNode the daceasedEstimatedAgeNode to get the lowValue from.
     */
    public void setDeceasedEstimatedAgeNode(DeceasedEstimatedAgeNode daceasedEstimatedAgeNode) {
        AgeRangeFieldHandler handler = daceasedEstimatedAgeNode.getAgeRangeHandler();
        if (handler != null) {
            setAgeAtDeath(AgeRange.getByLowValue(handler.getLowValue()));
        } else if (daceasedEstimatedAgeNode.getCodeNode().getOriginalText().equals(
                AgeRange.PREBIRTH.getOriginalText())) {
            setAgeAtDeath(AgeRange.PREBIRTH);
        } else {
            setAgeAtDeath(AgeRange.UNKNOWN);
        }
        
    }
}
