/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web.test;

import java.io.IOException;
import java.net.URL;

import javax.xml.xpath.XPathExpressionException;

import gov.hhs.fhh.service.HealthVaultContext;
import gov.hhs.fhh.service.HealthVaultLocal;
import gov.hhs.fhh.service.PersonInfo;
import gov.hhs.fhh.web.Settings;

/**
 * @author smatyas
 *
 */
public class HealthVaultStub implements HealthVaultLocal {

    /* (non-Javadoc)
     * @see gov.hhs.fhh.service.HealthVaultLocal#getFullName(gov.hhs.fhh.service.PersonInfo)
     */
    public String getFullName(PersonInfo personInfo) throws XPathExpressionException, IOException {
        return personInfo.getPersonName();
    }

    /* (non-Javadoc)
     * @see gov.hhs.fhh.service.HealthVaultLocal#getPersonInfo(java.lang.String, gov.hhs.fhh.service.PersonInfo)
     */
    public void getPersonInfo(String userAuthToken, PersonInfo person) throws XPathExpressionException {
    }

    /* (non-Javadoc)
     * @see gov.hhs.fhh.service.HealthVaultLocal#getSessionToken()
     */
    public String getSessionToken() {
        return null;
    }

    public void removeFamilyHistories(PersonInfo personInfo) {
        // TODO Auto-generated method stub
        
    }

    /* (non-Javadoc)
     * @see gov.hhs.fhh.service.HealthVaultLocal#getAuthenicationURL(gov.hhs.fhh.service.HealthVaultContext, java.lang.String)
     */
    public StringBuffer getAuthenicationURL(HealthVaultContext hvContext, String redirectUrl) {
        return new StringBuffer(Settings.INSTANCE.getSetting("application.base.url"));
    }

    /* (non-Javadoc)
     * @see gov.hhs.fhh.service.HealthVaultLocal#getShellUrl()
     */
    public URL getShellUrl() {
        return null;
    }

}
