create table disease (subType varchar(31) not null, id bigint not null auto_increment, originalText varchar(255), code varchar(50), codeSystemName varchar(255), codeSystem varchar(255), codeSystemVersion varchar(255), abbreviation varchar(255), parent_id bigint, primary key (id));
create table disease_displaystring (disease_id bigint not null, displayStrings_id bigint not null, primary key (disease_id, displayStrings_id), unique (displayStrings_id));
create table displaystring (id bigint not null auto_increment, appDisplay varchar(255), language varchar(50) not null, displayName varchar(255), primary key (id));
create table ethnicity (subType varchar(31) not null, id bigint not null auto_increment, originalText varchar(255), code varchar(50), codeSystemName varchar(255), codeSystem varchar(255), codeSystemVersion varchar(255), parent_id bigint, primary key (id));
create table ethnicity_displaystring (ethnicity_id bigint not null, displayStrings_id bigint not null, primary key (ethnicity_id, displayStrings_id), unique (displayStrings_id));
create table race (subType varchar(31) not null, id bigint not null auto_increment, originalText varchar(255), code varchar(50), codeSystemName varchar(255), codeSystem varchar(255), codeSystemVersion varchar(255), parent_id bigint, primary key (id));
create table race_displaystring (race_id bigint not null, displayStrings_id bigint not null, primary key (race_id, displayStrings_id), unique (displayStrings_id));
alter table disease add index disease_parent_fk (parent_id), add constraint disease_parent_fk foreign key (parent_id) references disease (id);
alter table disease_displaystring add index disease_codeable_fk (disease_id), add constraint disease_codeable_fk foreign key (disease_id) references disease (id);
alter table disease_displaystring add index disease_displaystring_fk (displayStrings_id), add constraint disease_displaystring_fk foreign key (displayStrings_id) references displaystring (id);
alter table ethnicity add index ethnicity_parent_fk (parent_id), add constraint ethnicity_parent_fk foreign key (parent_id) references ethnicity (id);
alter table ethnicity_displaystring add index ethnicity_codeable_fk (ethnicity_id), add constraint ethnicity_codeable_fk foreign key (ethnicity_id) references ethnicity (id);
alter table ethnicity_displaystring add index ethnicity_displaystring_fk (displayStrings_id), add constraint ethnicity_displaystring_fk foreign key (displayStrings_id) references displaystring (id);
alter table race add index race_parent_fk (parent_id), add constraint race_parent_fk foreign key (parent_id) references race (id);
alter table race_displaystring add index race_codeable_fk (race_id), add constraint race_codeable_fk foreign key (race_id) references race (id);
alter table race_displaystring add index race_displaystring_fk (displayStrings_id), add constraint race_displaystring_fk foreign key (displayStrings_id) references displaystring (id);
