/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web;

import gov.hhs.fhh.service.GenericServiceLocal;
import gov.hhs.fhh.service.PersonServiceLocal;
import gov.hhs.fhh.service.locator.JndiServiceLocator;
import gov.hhs.fhh.service.locator.ServiceLocator;

/**
 * @author Scott Miller
 */
public final class FhhRegistry {

    private static final FhhRegistry FHH_REGISTRY = new FhhRegistry();
    private ServiceLocator serviceLocator;

    /**
     * Constructor for the singleton instance.
     */
    private FhhRegistry() {
        this.serviceLocator = new JndiServiceLocator();
    }

    /**
     * @return the serviceLocator
     */
    public ServiceLocator getServiceLocator() {
        return this.serviceLocator;
    }

    /**
     * @param serviceLocator the serviceLocator to set
     */
    public void setServiceLocator(ServiceLocator serviceLocator) {
        this.serviceLocator = serviceLocator;
    }

    /**
     * @return the FHH_REGISTRY
     */
    public static FhhRegistry getInstance() {
        return FHH_REGISTRY;
    }

    /**
     * Gets the generic service from the service locator.
     * @return the service.
     */
    public static GenericServiceLocal getGenericService() {
        return getInstance().getServiceLocator().getGenericService();
    }
    
    /**
     * Gets the person service from the service locator.
     * @return the service.
     */
    public static PersonServiceLocal getPersonService() {
        return getInstance().getServiceLocator().getPersonService();
    }
}