/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.data;

import java.util.Map;

import com.fiveamsolutions.nci.commons.data.persistent.PersistentObject;

/**
 * @author bhumphrey
 * 
 */
public interface Disease extends Comparable<Disease>, Codeable, PersistentObject {

    /**
     * @return the displayStrings
     */
    Map<String, DisplayString> getDisplayStrings();

    /**
     * CompareTo function used for sorting a Disease drop down list. System Diseases are displayed in alphabetical order
     * first followed by user entered diseases. The option to add a new disease appears last in the list.
     * 
     * @param d object to compare to
     * @return int representing the objects ordering in the list
     */
    int compareTo(Disease d);

    /**
     * @return the parent
     */
    Disease getParent();

    /**
     * @return the abbreviation
     */
    String getAbbreviation();

    /**
     * @return the abbreviation
     */
    String getGeneratedAbbreviation();

    /**
     * @return the abbreviation
     */
    String getEscapedGeneratedAbbreviation();

    /**
     * @return the string to display on reports
     */
    String getReportDisplay();

    /**
     * @return the string to display on reports
     */
    String getEscapedReportDisplay();

    /**
     * @return the string to display on reports
     */
    String getEscapedOriginalText();

    /**
     * @return true if the Disease is a User entered Disease (no SNOMED code)
     */
    boolean isOther();

   
    /**
     * @param obj - object to compare to.
     * @return if two diseases are equal.
     */
    boolean equals(Object obj);
    

}