/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.data;

import gov.hhs.fhh.data.util.DataEstimatedAgeNode;
import gov.hhs.fhh.data.util.RelationshipHolderNode;
import gov.hhs.fhh.data.util.RelativeCodeNode;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * @author bpickeral
 * 
 */
public class Relative extends Person {
    private static final long serialVersionUID = 1L;
    private static final boolean TRUE = true;
    private String code;
    private String livingStatus;
    private Disease causeOfDeath;
    private AgeRange ageAtDeath;
    private String birthTime;
    private AgeRange estimatedAgeRange;
    // Used by castor when importing, mother and father may not exist at the time we get the
    // Ids, need to set Mother and father link after importing all relatives
    private Long motherId;
    private Long fatherId;

    /**
     * Default constructor.
     */
    public Relative() {
        // default constructor
        super();
    }

    /**
     * Copy constructor.
     * 
     * @param r the Relative object to copy from.
     */
    public Relative(Relative r) {
        super(r);
        this.code = r.code;
        this.livingStatus = r.livingStatus;
        this.causeOfDeath = r.causeOfDeath;
        this.ageAtDeath = r.ageAtDeath;
        this.birthTime = r.birthTime;
        this.motherId = r.motherId;
        this.fatherId = r.fatherId;
        this.estimatedAgeRange = r.getEstimatedAgeRange();
    }

    /**
     * Copy constructor for parent.
     * 
     * @param p the Parent object to copy from.
     */
    public Relative(Person p) {
        super(p);
        this.code = RelativeCode.SELF.toString();
    }

    /**
     * Copy constructor for parent.
     * 
     * @param p the Parent object to copy from.
     * @param r the RelativeCode to copy from.
     */
    @SuppressWarnings("PMD.ConstructorCallsOverridableMethod")
    public Relative(Person p, RelativeCode r) {
        super(p);
        code = r.toString();
        if (p instanceof Relative) {
            this.livingStatus = ((Relative) p).getLivingStatus();
            this.causeOfDeath = ((Relative) p).getCauseOfDeath();
            this.ageAtDeath = ((Relative) p).getAgeAtDeath();
            this.birthTime = ((Relative) p).getBirthTime();
            this.motherId = ((Relative) p).getMotherId();
            this.fatherId = ((Relative) p).getFatherId();
        } 
    }

    /**
     * Copy constructor for parent, used by reindex - so mother and father id are not copied.
     * 
     * @param p the Parent object to copy from.
     * @param r the RelativeCode to copy from.
     * @param reindex boolean indicates whether this is being used for a reindex
     */
    @SuppressWarnings("PMD.ConstructorCallsOverridableMethod")
    public Relative(Person p, RelativeCode r, boolean reindex) {
        super(p);
        code = r.toString();
        if (p instanceof Relative && reindex) {
            this.livingStatus = ((Relative) p).getLivingStatus();
            this.causeOfDeath = ((Relative) p).getCauseOfDeath();
            this.ageAtDeath = ((Relative) p).getAgeAtDeath();
            this.birthTime = ((Relative) p).getBirthTime();
        } 
    }

    /**
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code the code to set
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return the code enum
     */
    public RelativeCode getCodeEnum() {
        return RelativeCode.getByValue(code);
    }
    
    /**
     * @return the living status enum
     */
    public LivingStatus getLivingStatusEnum() {
        return LivingStatus.getByValue(livingStatus);
    }

    /**
     * This method is used only by Castor. Since the relative xml node is different from the person node and seperate
     * from the code node, we need a way to create a relationshipHolder node while keeping the code node outside of
     * relationshipHolder.
     * 
     * @return RelationshipHolderNode
     */
    public RelationshipHolderNode getRelationshipHolderNode() {
        RelationshipHolderNode node = new RelationshipHolderNode(this);
        // Add Cause of death to Clinical Observations
        if (getCauseOfDeath() != null) {
            ClinicalObservation causeOfDeathObs = new ClinicalObservation();
            causeOfDeathObs.setDisease(getCauseOfDeath());
            causeOfDeathObs.setCauseOfDeath(TRUE);
            node.getObservations().add(causeOfDeathObs);
        }
        // Set the parent node containing the id of the parent
        Relative parentNode = null;
        if (getMother() != null) {
            parentNode = new Relative();
            parentNode.setId(getMother().getId());
            parentNode.setCode(RelativeCode.NMTH.toString());
        } else if (getFather() != null) {
            parentNode = new Relative();
            parentNode.setId(getFather().getId());
            parentNode.setCode(RelativeCode.NFTH.toString());
        }
        node.setParentNode(parentNode);
        return node;
    }

    /**
     * This method is used only by Castor to set the RelationshipHolderNode.
     * 
     * @param node the RelativeCodeNode containing the code value
     */
    public void setRelationshipHolderNode(RelationshipHolderNode node) {
        // Get cause of death from Clinical Observations
        for (ClinicalObservation obs : node.getObservations()) {
            if (obs.isCauseOfDeath()) {
                setCauseOfDeath(obs.getDisease());
            } else {
                getObservations().add(obs);
            }
        }

        setId(node.getId());
        setName(node.getName());
        setDateOfBirth(node.getDateOfBirth());
        setGender(node.getGender());
        setEthnicities(node.getEthnicities());
        setRaces(node.getRaces());
        setAgeAtDeath(node.getAgeAtDeath());
        setLivingStatus(node.getLivingStatus());
        setBirthTime(node.getBirthTime());
        setAdopted(node.isAdopted());
        setTwinStatus(node.getTwinStatus());
        setWeight(node.getWeight());
        setHeight(node.getHeight());
        setParentIds(node);
        setCompletedForm(node.isCompletedForm());
        setEstimatedAgeRange(node.getEstimatedAgeRange());

        if (getBirthTime() != null || getEstimatedAgeRange() != null) {
            setLivingStatus(LivingStatus.YES.toString());
        }
    }

    /**
     * Sets the mother or father id using the parent stored in the RelationshipHolderNode.
     * 
     * @param node RelationshipHolderNode containing parent's ID
     */
    private void setParentIds(RelationshipHolderNode node) {
        Relative parentNode = node.getParentNode();
        if (node.getParentNode() != null) {
            if (RelativeCode.NMTH.toString().equals(parentNode.getCode())) {
                setMotherId(parentNode.getId());
            } else {
                setFatherId(parentNode.getId());
            }
        }
    }
    
    /**
     * Returns boolean indicating if person can be removed from the family tree.
     * 
     * @return true if person is removable, otherwise false
     */
    public boolean isRemovable() {
        boolean isRemovable = true;
        switch (getCodeEnum()) {
        case PGRMTH:
        case PGRFTH:
        case MGRMTH:
        case MGRFTH:
        case NMTH:
        case NFTH:
            isRemovable = false;
            break;
        default:
        }
        return isRemovable;
    }

    /**
     * Returns boolean indicating if person is deceased.
     * 
     * @return true if person is deceased, otherwise false
     */
    public boolean isDeceased() {
        boolean isDeceased = false;
        if (livingStatus != null && livingStatus.equals(LivingStatus.NO.toString())) {
            isDeceased = true;
        }
        return isDeceased;
    }

    /**
     * Used by Castor to generate the deceased indicator node if the relative is deceased. Note: isDeceased should be
     * used outside of Castor as this function returns null in the case that the relative is alive.
     * 
     * @return true string if person is deceased, otherwise null
     */
    public String getDeceasedIndicator() {
        if (isDeceased()) {
            return TRUE_STRING;
        }
        return null;
    }

    /**
     * Used by Castor to set the living status of a relative.
     * 
     * @param indicator string representing if the relative is deceased
     */
    public void setDeceasedIndicator(String indicator) {
        if (indicator.equals(TRUE_STRING)) {
            setLivingStatus(LivingStatus.NO.toString());
        }
    }
    
    /**
     * @return the DataEstimatedAgeNode
     */
    public DataEstimatedAgeNode getDataEstimatedAgeNode() {
        return getEstimatedAgeRange() != null ? getEstimatedAgeRange().getAsDataEstimatedAgeNode() : null;
    }
    
    /**
     * Sets the ageRange based on the dataEstimatedAgeNode passed in.
     * @param dataEstimatedAgeNode the dataEstimatedAgeNode to get the lowValue from.
     */
    public void setDataEstimatedAgeNode(DataEstimatedAgeNode dataEstimatedAgeNode) {
        setEstimatedAgeRange(AgeRange.fromDataEstimatedAgeNode(dataEstimatedAgeNode));
    }

    /**
     * This method is used only by Castor to represent a Relative Code Node.
     * 
     * @return the RelativeCodenode.
     */
    public RelativeCodeNode getRelativeCodeNode() {
        return new RelativeCodeNode(code);
    }

    /**
     * This method is used only by Castor to set the relative code.
     * 
     * @param node the RelativeCodeNode containing the code value
     */
    public void setRelativeCodeNode(RelativeCodeNode node) {
        code = node.getCode();
    }

    /**
     * @return the livingStatus
     */
    public String getLivingStatus() {
        return livingStatus;
    }

    /**
     * @param livingStatus the livingStatus to set
     */
    public void setLivingStatus(String livingStatus) {
        this.livingStatus = livingStatus;
    }

    /**
     * @return the causeOfDeath
     */
    public Disease getCauseOfDeath() {
        return causeOfDeath;
    }

    /**
     * @param causeOfDeath the causeOfDeath to set
     */
    public void setCauseOfDeath(Disease causeOfDeath) {
        this.causeOfDeath = causeOfDeath;
    }

    /**
     * @return the birthTime
     */
    public String getBirthTime() {
        return birthTime;
    }

    /**
     * @param birthTime the birthTime to set
     */
    public void setBirthTime(String birthTime) {
        this.birthTime = birthTime;
    }

    /**
     * @return the motherId
     */
    public Long getMotherId() {
        return motherId;
    }

    /**
     * @param motherId the motherId to set
     */
    public void setMotherId(Long motherId) {
        this.motherId = motherId;
    }

    /**
     * @return the fatherId
     */
    public Long getFatherId() {
        return fatherId;
    }

    /**
     * @param fatherId the fatherId to set
     */
    public void setFatherId(Long fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * {@inheritDoc}
     */
    public String toString() {
        return new ToStringBuilder(this).append(getName()).append(getCode()).toString();
    }

    /**
     * @return the ageAtDeath
     */
    public AgeRange getAgeAtDeath() {
        return ageAtDeath;
    }

    /**
     * @param ageAtDeath the ageAtDeath to set
     */
    public void setAgeAtDeath(AgeRange ageAtDeath) {
        this.ageAtDeath = ageAtDeath;
    }

    /**
     * @return the estimatedAgeRange
     */
    public AgeRange getEstimatedAgeRange() {
        return estimatedAgeRange;
    }

    /**
     * @param estimatedAgeRange the estimatedAgeRange to set
     */
    public void setEstimatedAgeRange(AgeRange estimatedAgeRange) {
        this.estimatedAgeRange = estimatedAgeRange;
    }
}
