/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web.integration;

import static org.junit.Assert.assertEquals;
import gov.hhs.fhh.data.Person;
import gov.hhs.fhh.web.TestProperties;
import gov.hhs.fhh.web.action.FamilyHistoryAction;
import gov.hhs.fhh.web.test.AbstractFhhWebTest;
import gov.hhs.fhh.web.util.FhhHttpSessionUtil;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Collection;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang.SerializationUtils;
import org.junit.Test;

/**
 * @author smatyas
 * 
 */
public class SerializeXMLFilesTest extends AbstractFhhWebTest {

    @SuppressWarnings("unchecked")
    @Test
    public void testLoadAndSerialize() throws Exception {
        File directory = new File(TestProperties.getWebBaseDir() + "/src/test/resources/testfamilyhistoryfiles/");
        System.err.println(directory);
        Collection<File> listFiles = FileUtils.listFiles(directory, new String[] { "xml" }, false);
        for (File file : listFiles) {
            System.err.println(file);
            importAndSerialize(file);
        }
    }

    private void importAndSerialize(File file) throws FileNotFoundException, IOException {
        FamilyHistoryAction action = new FamilyHistoryAction();
        FhhHttpSessionUtil.getSession().setAttribute("80000000", new Person());
        FhhHttpSessionUtil.getSession().setAttribute(FhhHttpSessionUtil.ROOT_KEY, "80000000");
        action.setImportedFile(file);

        assertEquals("importComplete", action.importXmlFile());
        Person person = action.getPerson();
        byte[] serializedPerson = SerializationUtils.serialize(person);

        FileOutputStream fos = null;
        try {
            String fosPath = TestProperties.getWebBaseDir() + "/target/" + file.getName() + ".ser";
            System.err.println(fosPath);
            fos = new FileOutputStream(new File(fosPath));
            fos.write(serializedPerson);
        } finally {
            if (fos != null) {
                IOUtils.closeQuietly(fos);
            }
        }
    }
}
