/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.data.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;

import org.junit.Test;

/**
 * @author bpickeral
 *
 */
public class FormatUtilsTest {
    private final Integer AGE = 55;
    private final String INCORRECT_LENGTH = "01/01/07";
    private final String INVALID_DATE = "01/01/YYYY";
    private final String VALID_DATE = "01/01/1970";
    
    @Test
    public void convertAgeToYearTest() {
        Calendar calendar = Calendar.getInstance();
        assertEquals(FormatUtils.convertAgeToYear(AGE), Integer.toString(calendar.get(Calendar.YEAR) - AGE));
    }
    
    @Test
    public void convertStringToDateTest() {
        assertNull(FormatUtils.convertStringToDate(INCORRECT_LENGTH));
        
        assertNull(FormatUtils.convertStringToDate(INVALID_DATE));
        
        SimpleDateFormat format = new SimpleDateFormat(FormatUtils.DATE_FORMAT_STRING, Locale.US);
        format.setLenient(false);

        try {
            assertEquals(format.parse(VALID_DATE), FormatUtils.convertStringToDate(VALID_DATE));
        } catch(Exception e) {
            fail("Exception occurred while parsing date");
        }
        
    }
}
