/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.htm;

import gov.hhs.fhh.data.RelativeCode;
import gov.hhs.fhh.data.util.htmimport.HTMImporter;

import org.w3c.dom.Node;

import com.fiveamsolutions.hl7.model.mfhp.Gender;

/**
 * @author bhumphrey
 * 
 */
public class InputNode {
    private String name;
    private String value;
    private Node node;
    private final HTMImporter importer = new HTMImporter();

    /**
     * Constructor.
     */
    public InputNode() {
        name = null;
        value = null;
        node = null;
    }

    /**
     * Parameterized Constructor.
     * 
     * @param name String to set
     * @param value String to set
     * @param node Node to set
     */
    public InputNode(String name, String value, Node node) {
        this.name = name;
        this.value = value;
        this.node = node;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the value
     */
    public String getValue() {
        return value;
    }

    /**
     * @param value the value to set
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * @return the node
     */
    public Node getNode() {
        return node;
    }

    /**
     * @param node the node to set
     */
    public void setNode(Node node) {
        this.node = node;
    }

    /**
     * Returns the relative code associated with the input node. The legacy relative codes are contained within the name
     * attribute of the input node.
     * 
     * @return the RelativeCode associated with the input node.
     */
    public RelativeCode getRelativeCode() {
        RelativeCode relativeCode = null;
        relativeCode = importer.convertLegacyCodeToHTMRelationship(getName()).getRelativeCode();
        return relativeCode;
    }

    /**
     * Converts this htm InputNode to the corresponding gender constant. The matching is done by htmValue. Returns null
     * if no match is found.
     * 
     * @return the corresponding Gender constant
     */
    public Gender toGenderNode() {
        for (Gender gender : Gender.values()) {
            if (gender.getHtmValue().equals(getValue())) {
                return gender;
            }
        }
        return null;
    }
}
