/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web.interceptor;

import static org.junit.Assert.assertEquals;
import gov.hhs.fhh.service.util.CurrentLanguageHolder;
import gov.hhs.fhh.web.test.AbstractFhhWebTest;

import java.util.HashMap;

import org.apache.struts2.ServletActionContext;
import org.junit.Before;
import org.junit.Test;

import com.opensymphony.xwork2.interceptor.I18nInterceptor;
import com.opensymphony.xwork2.mock.MockActionInvocation;
import com.opensymphony.xwork2.mock.MockActionProxy;
import com.opensymphony.xwork2.util.ValueStackFactory;

/**
 * @author Steve Lustbader
 */
@SuppressWarnings("unchecked")
public class CustomI18nInterceptorTest extends AbstractFhhWebTest {

    MockActionInvocation invocation;

    @Before
    public void setUp() {
        ServletActionContext.getContext().setParameters(new HashMap());
        ServletActionContext.getContext().setSession(new HashMap());
        invocation = new MockActionInvocation();
        invocation.setProxy(new MockActionProxy());
        invocation.setInvocationContext(ServletActionContext.getContext());
        invocation.setStack(ValueStackFactory.getFactory().createValueStack());
    }

    @Test
    public void testInterceptor() throws Exception {
        I18nInterceptor i18Interceptor = new I18nInterceptor();
        CustomI18nInterceptor interceptor = new CustomI18nInterceptor();

        i18Interceptor.intercept(invocation);
        interceptor.intercept(invocation);
        //assertEquals("en", CurrentLanguageHolder.getCurrentLanguage());

        ServletActionContext.getContext().getParameters().put("request_locale", "es");
        i18Interceptor.intercept(invocation);
        interceptor.intercept(invocation);
        //assertEquals("es", CurrentLanguageHolder.getCurrentLanguage());

        ServletActionContext.getContext().getParameters().put("request_locale", "en");
        i18Interceptor.intercept(invocation);
        interceptor.intercept(invocation);
        //assertEquals("en", CurrentLanguageHolder.getCurrentLanguage());
    }

}
