/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web.converter;

import gov.hhs.fhh.data.Disease;
import gov.hhs.fhh.service.locator.FhhRegistry;
import gov.hhs.mfhp.model.Observation;

import java.util.HashMap;
import java.util.Map;

import com.fiveamsolutions.nci.commons.service.GenericDataService;
import com.fiveamsolutions.nci.commons.web.struts2.converter.AbstractPersistentObjectTypeConverter;

/**
 * @author Scott Miller
 */
public class PersistentObjectTypeConverter extends AbstractPersistentObjectTypeConverter {

    private final Map<Class, Class> mappedInterfaces;
    
    
    /**
     * 
     */
    public PersistentObjectTypeConverter() {
        super();
        mappedInterfaces = new HashMap<Class, Class>();
        mappedInterfaces.put(Disease.class, Observation.class);
        
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected GenericDataService getGenericDataService() {
        return FhhRegistry.getGenericService();
    }

    /**
     * {@inheritDoc} 
     * @see com.fiveamsolutions.nci.commons.web.struts2.converter.
     * AbstractPersistentObjectTypeConverter#convertFromString(java.util.Map, java.lang.String[], java.lang.Class)
     */
    @Override
    public Object convertFromString(Map map, String[] values, Class toClass) {
        // TODO Auto-generated method stub
        if (mappedInterfaces.containsKey(toClass)) {
            return super.convertFromString(map, values, mappedInterfaces.get(toClass));
        }
        return super.convertFromString(map, values, toClass);
    }
    
}