/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the "software") and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.service.util;

import gov.hhs.fhh.data.Disease;
import gov.hhs.fhh.data.RelativeReport;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.apache.commons.collections.set.ListOrderedSet;

import com.fiveamsolutions.hl7.model.age.AgeRangeEnum;

/**
 * Holds information required to create pdf.
 * RelativeDraw of person to be drawn
 * RelativeReport Set of relatives configured for the report
 * legendList the diseases to show on the report legend
 * ageRangeEnums internationalized values for age ranges of diseases
 * legendLabels internationalized values for common diseases in legend
 * @author lpower
 */
public class PdfDataContainer {
    
    private RelativeDraw relativeDraw;
    private Map<AgeRangeEnum, String> ageRangeEnums = new HashMap<AgeRangeEnum, String>();
    private Map<String, String> legendLabels = new HashMap<String, String>();
    private Set<RelativeReport> relativeReports = new ListOrderedSet();
    private Set<Disease> legendList = new HashSet<Disease>();

    /**
     * @return the relativeDraw
     */
    public RelativeDraw getRelativeDraw() {
        return relativeDraw;
    }
    
    /**
     * @param relativeDraw the relativeDraw to set
     */
    public void setRelativeDraw(RelativeDraw relativeDraw) {
        this.relativeDraw = relativeDraw;
    }
    
    /**
     * @return the ageRangeEnums
     */
    public Map<AgeRangeEnum, String> getAgeRanges() {
        return ageRangeEnums;
    }
    
    /**
     * @param ageRangeEnumsParam the ageRangeEnums to set.
     */
    public void setAgeRanges(Map<AgeRangeEnum, String> ageRangeEnumsParam) {
        this.ageRangeEnums = ageRangeEnumsParam;
    }
    
    /**
     * @return the legendValues
     */
    public Map<String, String> getLegendLabels() {
        return legendLabels;
    }
    
    /**
     * @param legendLabels the legendValues to set
     */
    public void setLegendLabels(Map<String, String> legendLabels) {
        this.legendLabels = legendLabels;
    }
    
    /**
     * @return the relativeReports
     */
    public Set<RelativeReport> getRelativeReports() {
        return relativeReports;
    }
    
    /**
     * @param relativeReports the relativeReports to set
     */
    public void setRelativeReports(Set<RelativeReport> relativeReports) {
        this.relativeReports = relativeReports;
    }

    /**
     * @return the legendList
     */
    public Set<Disease> getLegendList() {
        return legendList;
    }

    /**
     * @param legendList the legendList to set
     */
    public void setLegendList(Set<Disease> legendList) {
        this.legendList = legendList;
    }
}