/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.data.util.htmimport;

import gov.hhs.fhh.data.RelativeCode;

import java.util.ArrayList;
import java.util.List;

/**
 * @author bpickeral
 * Class is used in conjunction with Castor to store input nodes from a legacy (v1.x)
 * FHH file.
 */
public class HTMNode {
    private final List<InputNode> inputNodes = new ArrayList<InputNode>();
    
    // Field is not used by Castor.  The RelativeCode is set when we first separate the InputNode objects
    // into separate HTMNode objects for later identification.
    private final RelativeCode relativeCode;
    private final Integer relativeNum;
    
    /**
     * Default constructor used by Castor.
     */
    public HTMNode() {
        relativeCode = null;
        relativeNum = null;
    }
    
    /**
     * Constructor with <code>RelativeCode</code> and relative number parameter.
     * @param code Relative code to set
     * @param relativeNum Integer the number of the relative type as it appeared in the
     *  legacy input. Fixed relatives (parents and grandparents) should have a null relativeNum
     */
    public HTMNode(RelativeCode code, Integer relativeNum) {
        this.relativeCode = code;
        this.relativeNum = relativeNum;
    }
    
    /**
     * Creates the relative name as it appears in the input node of the legacy input.  Fixed relatives are named 
     *  using only the <code>htmValue</code> of the <code>RelativeCode</code>. 
     * @return String htmName as it appears in the legacy input
     */
    public String getHTMName() {
        StringBuffer name = new StringBuffer();
        name.append(getRelativeCode().getHtmValue());
        if (getRelativeNum() != null) {
            name.append(getRelativeNum().toString());
        }
        return name.toString();
    }

    /**
     * @return the inputNodes
     */
    public List<InputNode> getInputNodes() {
        return inputNodes;
    }

    /**
     * @return the relativeCode
     */
    public RelativeCode getRelativeCode() {
        return relativeCode;
    }

    /**
     * @return the relativeNum
     */
    public Integer getRelativeNum() {
        return relativeNum;
    }
}
