/**
 *
 * Family Health History Portal
 * END USER AGREEMENT
 *
 * The U.S. Department of Health & Human Services ("HHS") hereby irrevocably
 * grants to the user a non-exclusive, royalty-free right to use, display,
 * reproduce, and distribute this Family Health History portal software
 * (the "software") and prepare, use, display, reproduce and distribute
 * derivative works thereof for any commercial or non-commercial purpose by any
 * party, subject only to the following limitations and disclaimers, which
 * are hereby acknowledged by the user.
 *
 * User agrees that it will not degrade the standards-based format of the software
 * by materially altering the program architecture or data structure in a way
 * that would render the data generated by the altered software incompatible
 * with the original software. The intention of this clause is to ensure the
 * long-term interoperability of family history information gathered by different
 * versions of the tool.
 *
 * User agrees that this END USER AGREEMENT will be provided to any party to
 * whom user distributes the software, and that it will apply to the distributee.
 *
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS
 * trademarks without permission from HHS, and will not imply endorsement of
 * its product by HHS or the Surgeon General.
 *
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED,
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT,
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 *
 */
package gov.hhs.fhh.web.action;

import gov.hhs.fhh.data.Person;
import gov.hhs.fhh.data.util.FormatUtils;
import gov.hhs.fhh.web.data.HeightUnitHolder;
import gov.hhs.fhh.web.util.PersonActionUtils;

import org.apache.commons.lang.StringUtils;

import com.fiveamsolutions.hl7.model.mfhp.Gender;
import com.fiveamsolutions.hl7.model.mfhp.WeightUnit;

/**
 * @author bpickeral
 *
 */
public class AbstractEditPersonAction extends AbstractFHHAction {
    private static final long serialVersionUID = 316273314L;

    private Person person;
    private String dateOfBirthString;
    private String heightUnit1;
    private String heightUnit2;
    private String heightMetric;
    private String weightString;

    /**
     * Set value in the UI based on the values in Person.
     */
    protected void setupDateOfBirth() {
        if (getPerson().getDateOfBirth() != null) {
            setDateOfBirthString(FormatUtils.format(getPerson().getDateOfBirth()));
        }
    }

    /**
     * Set value in the UI based on the values in Person.
     */
    protected void setupHeight() {
        final HeightUnitHolder holder = PersonActionUtils.getInstance().extractHeightUnits(person);
        setHeightUnit1(holder.getHeightUnit1());
        setHeightUnit2(holder.getHeightUnit2());
        setHeightMetric(holder.getHeightMetric());
    }

    /**
     * Set value in the UI based on the values in Person.
     */
    protected void storeWeight() {
        if (!StringUtils.isEmpty(getWeightString())) {
            getPerson().getWeight().setValue(Integer.valueOf(getWeightString()));
        }
    }

    /**
     * @return the gender enums
     */
    public Gender[] getGenderEnums() {
        return Gender.values();
    }

    /**
     * @return the weight unit enums
     */
    public WeightUnit[] getWeightUnitEnums() {
        return WeightUnit.values();
    }

    /**
     * @return the dateOfBirthString
     */
    public String getDateOfBirthString() {
        return dateOfBirthString;
    }

    /**
     * @param dateOfBirthString the dateOfBirthString to set
     */
    public void setDateOfBirthString(String dateOfBirthString) {
        this.dateOfBirthString = dateOfBirthString;
    }

    /**
     * @return the heightUnit1
     */
    public String getHeightUnit1() {
        return heightUnit1;
    }

    /**
     * @param heightUnit1 the heightUnit1 to set
     */
    public void setHeightUnit1(String heightUnit1) {
        this.heightUnit1 = heightUnit1;
    }

    /**
     * @return the heightUnit2
     */
    public String getHeightUnit2() {
        return heightUnit2;
    }

    /**
     * @param heightUnit2 the heightUnit2 to set
     */
    public void setHeightUnit2(String heightUnit2) {
        this.heightUnit2 = heightUnit2;
    }

    /**
     * @return the heightMetric
     */
    public String getHeightMetric() {
        return heightMetric;
    }

    /**
     * @param heightMetric the heightMetric to set
     */
    public void setHeightMetric(String heightMetric) {
        this.heightMetric = heightMetric;
    }

    /**
     * @return the weightString
     */
    public String getWeightString() {
        return weightString;
    }

    /**
     * @param weightString the weightString to set
     */
    public void setWeightString(String weightString) {
        this.weightString = weightString;
    }

    /**
     * @return the person
     */
    public Person getPerson() {
        return person;
    }

    /**
     * @param person the person to set
     */
    public void setPerson(Person person) {
        this.person = person;
    }

}
