/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web.action;

import gov.hhs.fhh.data.ClinicalObservation;
import gov.hhs.fhh.data.Person;
import gov.hhs.fhh.data.Relative;
import gov.hhs.fhh.data.RelativeCode;
import gov.hhs.fhh.web.util.FhhHttpSessionUtil;

import com.opensymphony.xwork2.ActionSupport;
import com.opensymphony.xwork2.Preparable;

/**
 * @author bpickeral
 *
 */
public class DroppedRelativesAction extends ActionSupport implements Preparable {
    private static final long serialVersionUID = 19266463L;
    private Person person;
    
    /**
     * {@inheritDoc}
     */
    public void prepare() {
        Person rootPerson = FhhHttpSessionUtil.getRootPerson();
        if (rootPerson != null) {
            setPerson(rootPerson);
        }
    }
    
    private void setupDroppedWarningMessages() {
        for (Relative relative : getPerson().getHtmImportDroppedRelatives()) {
            StringBuffer sb = new StringBuffer();
            sb.append(getText(RelativeCode.getByValue(relative.getCode()).getResourceKey()));
            sb.append(' ');
            if (relative.getName() != null) {
                sb.append(relative.getName());
                sb.append(' ');
            } 
            sb.append(getText("droppedRelatives.droppedMessage"));
            for (ClinicalObservation obs : relative.getObservations()) {
                sb.append(generateDiseaseMessage(obs));
            }
            addFieldError("warningMessages", sb.toString());
        }
    }
    
    private String generateDiseaseMessage(ClinicalObservation obs) {
        StringBuffer sb = new StringBuffer();
        String diseaseName;
        if (obs.getDisease().getOriginalText() != null) {
            diseaseName = obs.getDisease().getOriginalText();
        } else {
            diseaseName = obs.getDisease().getAppDisplay();
        }
        sb.append(' ' + diseaseName + ", " + getText(obs.getAgeRange().getResourceKey()) + '.');
        return sb.toString();
    }
    
    /**
     * Method invokes the dropped relatives page.
     * @return path String
     */
    public String droppedRelatives() {
        setupDroppedWarningMessages();
        return INPUT;
    }

    /**
     * @return the person
     */
    public Person getPerson() {
        return person;
    }

    /**
     * @param person the person to set
     */
    public void setPerson(Person person) {
        this.person = person;
    }
}
