/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.data.util;

import gov.hhs.fhh.data.ClinicalObservationCode;

/**
 * @author bpickeral
 * Class is used in conjunction with Castor to display code XML nodes for multiple
 * single value fields such as weight, bmi... 
 */
public class CodeNode {
    private Long id;
    private String code;
    private String codeSystemName;
    private String displayName;
    private String originalText;
    
    /**
     * Default constructor.
     */
    public CodeNode() {
        //Empty constructor.
    }
    
    /**
     * Parameterized constructor.
     * @param code to set
     * @param codeSystemName to set
     * @param displayName to set
     */
    public CodeNode(String code, String codeSystemName, String displayName) {
        this.code = code;
        this.codeSystemName = codeSystemName;
        this.displayName = displayName;
    }
    
    /**
     * Parameterized constructor.
     * @param code to set
     * @param codeSystemName to set
     * @param displayName to set
     * @param id to set
     * @param originalText to set
     */
    public CodeNode(String code, String codeSystemName, String displayName,
            Long id, String originalText) {
        this.code = code;
        this.codeSystemName = codeSystemName;
        this.displayName = displayName;
        this.id = id;
        this.originalText = originalText;
    }
    
    /**
     * ClinicalObservationCode constructor.
     * @param code ClinicalObservationCode to get values of code, codeSystemName,
     * and displayName
     */
    public CodeNode(ClinicalObservationCode code) {
        this.code = code.getCode();
        this.codeSystemName = code.getCodeSystemName();
        this.displayName = code.getDisplayName();
    }

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code the code to set
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return the codeSystemName
     */
    public String getCodeSystemName() {
        return codeSystemName;
    }

    /**
     * @param codeSystemName the codeSystemName to set
     */
    public void setCodeSystemName(String codeSystemName) {
        this.codeSystemName = codeSystemName;
    }

    /**
     * @return the displayName
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * @param displayName the displayName to set
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * @return the originalText
     */
    public String getOriginalText() {
        return originalText;
    }

    /**
     * @param originalText the originalText to set
     */
    public void setOriginalText(String originalText) {
        this.originalText = originalText;
    }
    
    
}
