/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.data;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

/**
 * @author bpickeral
 *
 */
public class GenderNodeTest {
    private final String CODE = "code";
    private final String CODE_SYS = "code sys";
    private final String DISP_NAME = "disp";
    private final String ORIG_TEXT = "orig text";
    
    @Test
    public void testCreateGenderNode() {
        GenderNode node = new GenderNode();
        node.setCode(CODE);
        node.setCodeSystemName(CODE_SYS);
        node.setDisplayName(DISP_NAME);
        node.setOriginalText(ORIG_TEXT);
        
        assertEquals(CODE, node.getCode());
        assertEquals(CODE_SYS, node.getCodeSystemName());
        assertEquals(DISP_NAME, node.getDisplayName());
        assertEquals(ORIG_TEXT, node.getOriginalText());
        
        GenderNode node2 = new GenderNode(CODE, CODE_SYS, DISP_NAME, false);
        assertEquals(CODE, node2.getCode());
        assertEquals(CODE_SYS, node2.getCodeSystemName());
        assertEquals(DISP_NAME, node2.getDisplayName());
        assertNull(node2.getOriginalText());
        
        node2 = new GenderNode(CODE, CODE_SYS, DISP_NAME, true);
        assertEquals(CODE, node2.getCode());
        assertEquals(CODE_SYS, node2.getCodeSystemName());
        assertEquals(DISP_NAME, node2.getDisplayName());
        assertEquals(DISP_NAME, node2.getOriginalText());
    }
}
