/**
 * 
 * Family Health History Portal 
 * END USER AGREEMENT
 * 
 * The U.S. Department of Health & Human Services (“HHS”) hereby irrevocably 
 * grants to the user a non-exclusive, royalty-free right to use, display, 
 * reproduce, and distribute this Family Health History portal software 
 * (the “software”) and prepare, use, display, reproduce and distribute 
 * derivative works thereof for any commercial or non-commercial purpose by any 
 * party, subject only to the following limitations and disclaimers, which 
 * are hereby acknowledged by the user.  
 * 
 * User agrees that it will not degrade the standards-based format of the software 
 * by materially altering the program architecture or data structure in a way 
 * that would render the data generated by the altered software incompatible 
 * with the original software. The intention of this clause is to ensure the 
 * long-term interoperability of family history information gathered by different 
 * versions of the tool.
 * 
 * User agrees that this END USER AGREEMENT will be provided to any party to 
 * whom user distributes the software, and that it will apply to the distributee.
 * 
 * User agrees that it will not use the HHS or Surgeon General logo or any HHS 
 * trademarks without permission from HHS, and will not imply endorsement of 
 * its product by HHS or the Surgeon General.
 * 
 * THIS SOFTWARE IS PROVIDED TO USER WITH NO WARRANTIES, EXPRESS OR IMPLIED, 
 * INCLUDING ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, 
 * OR THAT THE USE OF THE SOFWARE WILL NOT INFRINGE ANY PATENT, COPYRIGHT, 
 * TRADEMARK OR OTHER PROPRIETARY RIGHTS.
 * 
 */
package gov.hhs.fhh.web.action;

import gov.hhs.fhh.data.Person;
import gov.hhs.fhh.data.Relative;
import gov.hhs.fhh.data.RelativeBranch;
import gov.hhs.fhh.web.util.FhhCastorUtils;
import gov.hhs.fhh.web.util.FhhHttpSessionUtil;
import gov.hhs.fhh.web.util.FhhUtils;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;
import org.exolab.castor.mapping.MappingException;
import org.exolab.castor.xml.MarshalException;
import org.exolab.castor.xml.ValidationException;

import com.opensymphony.xwork2.ActionSupport;
import com.opensymphony.xwork2.Preparable;

/**
 * @author bpickeral
 *
 */
@SuppressWarnings("PMD.TooManyMethods")
public class FamilyHistoryAction extends ActionSupport implements Preparable {
    private static final long serialVersionUID = 1161714L;
    private static final Logger LOG = Logger.getLogger(FamilyHistoryAction.class);
    private static final String MAPPING_FILE = "/mapping.xml";
    private static final String HTM_MAPPING_FILE = "/htm_mapping.xml";
    private static final String IMPORT_ERROR = "Error importing file";
    private static final String IMPORT_COMPLETE = "importComplete";
    private static final String IMPORT_FAILED = "input";
    private static final String IMPORT_FIELD_NAME = "upload";
    private Person person;
    private File importedFile;
    private RelativeBranch relativeBranch;
    private boolean maintainState;
    private boolean create;
    private String removeRelativeId;

    /**
     * {@inheritDoc}
     */
    public void prepare() {
        if (FhhHttpSessionUtil.getRootKey() == null) {
            FhhHttpSessionUtil.storePersonInSession(new Person());
        }
        Person rootPerson = FhhHttpSessionUtil.getRootPerson();
        if (rootPerson != null) {
            setPerson(rootPerson);
            this.relativeBranch = new RelativeBranch(person);
        }
    }

    /**
     * @return success
     */
    public String start() {
        if (!maintainState) {
            setPerson(new Person());
            FhhHttpSessionUtil.storePersonInSession(getPerson());
            relativeBranch = null;
        }
        return SUCCESS;
    }

    /**
     * Method invokes the familyHistory page.
     *
     * @return path String
     */
    public String familyHistory() {
        return SUCCESS;
    }

    /**
     * Method invokes the familyHistoryDetail page.
     *
     * @return path String
     */
    public String familyHistoryDetail() {
        return SUCCESS;
    }

    /**
     * Method invokes the familyHistoryDetail page.
     *
     * @return path String
     */
    public String saveFamilyHistory() {
        return SUCCESS;
    }

    /**
     * Method invokes the familyHistoryDetail page.
     *
     * @return path String
     */
    public String importFamilyHistory() {
        return SUCCESS;
    }


    /**
     * Imports the Person Object to session.
     *
     * @return input
     */
    public String importXmlFile() {
        InputStream in = null;
        File file = getImportedFile();
        try {
            in = FileUtils.openInputStream(file);
            String fileStr = FhhCastorUtils.getInputStreamAsString(in);
            if (fileStr.contains("<?xml")) {
                importXMLFile(fileStr);
            } else {
                importHTMFile(fileStr);
            }   
        } catch (Exception e) {
            LOG.error(IMPORT_ERROR, e);
            addFieldError(IMPORT_FIELD_NAME, getText("importFamilyHistory.error.importingFile"));
            
            return IMPORT_FAILED;
        } finally {
            IOUtils.closeQuietly(in);
        }
        return IMPORT_COMPLETE;
    }
    
    /**
     * Populates the family Tree with attributes from a version 2.x FHH XML file.
     */
    private void importXMLFile(String xmlFile) throws MarshalException, 
        ValidationException, IOException, MappingException {
        setPerson((Person) FhhCastorUtils.unmarshallXMLFile(xmlFile, 
                this.getClass().getResource(MAPPING_FILE).getPath(), new Person()));
        getPerson().setCompletedForm(true);
        FhhHttpSessionUtil.setAttribute(FhhHttpSessionUtil.getRootKey(), getPerson());
        setPerson(FhhUtils.setupParents(this.person));
        FhhHttpSessionUtil.addAllUserEnteredDiseases(getPerson());
    }
    
    /**
     * Populates the family Tree with attributes from a version 1.x FHH HTM file.
     */
    private void importHTMFile(String htmFile) throws MarshalException,
        ValidationException, IOException, MappingException {
        Person p = (Person) FhhCastorUtils.unmarshallHTMFile(htmFile, 
                this.getClass().getResource(HTM_MAPPING_FILE).getPath(), new Person());
        setPerson(p);
        FhhHttpSessionUtil.setAttribute(FhhHttpSessionUtil.getRootKey(), getPerson());
    }
    
    /**
     * Action removes the relative of index relativeId and all of the relatives descendants from
     * the family tree.
     *
     * @return path String
     */
    public String removeRelative() {
        List<Relative> removeList = new ArrayList<Relative>();
        removeDescendants(person.getRelatives().get(Integer.valueOf(removeRelativeId)), removeList);
        person.getRelatives().remove((int) Integer.valueOf(removeRelativeId));
        for (Relative currRelative : removeList) {
            person.getRelatives().remove(currRelative);
        }
        this.relativeBranch = new RelativeBranch(person);
        return "familyHistory";
    }
    
    /**
     * Method adds relatives to the removeList that are parents of the relative passed in.  Method calls
     * removeDescendants on any descendants added to the removeList.
     * @param relativeRemoved The ancestor of the relatives to be removed.
     * @param removeList The list of relatives to be removed.
     */
    private void removeDescendants(Relative relativeRemoved, List<Relative> removeList) {
        for (Relative currRelative : person.getRelatives()) {
            if (relativeRemoved.equals(currRelative.getMother())
                    || relativeRemoved.equals(currRelative.getFather())) {
                removeList.add(currRelative);
                removeDescendants(currRelative, removeList);
            }
        }
    }

    /**
     * @return the person
     */
    public Person getPerson() {
        return person;
    }

    /**
     * @param person the person to set
     */
    public void setPerson(Person person) {
        this.person = person;
    }

    /**
     * @return the importedFile
     */
    public File getImportedFile() {
        return importedFile;
    }

    /**
     * @param importedFile the importedFile to set
     */
    public void setImportedFile(File importedFile) {
        this.importedFile = importedFile;
    }

    /**
     * @return the relativeBranch
     */
    public RelativeBranch getRelativeBranch() {
        return relativeBranch;
    }

    /**
     * @param relativeBranch the relativeBranch to set
     */
    public void setRelativeBranch(RelativeBranch relativeBranch) {
        this.relativeBranch = relativeBranch;
    }

    /**
     * @return the maintainState
     */
    public boolean isMaintainState() {
        return maintainState;
    }

    /**
     * @param maintainState the maintainState to set
     */
    public void setMaintainState(boolean maintainState) {
        this.maintainState = maintainState;
    }

    /**
     * @return is creating a new Person/Family History (from Home page)
     */
    public boolean isCreate() {
        return create;
    }

    /**
     * @param create true if are creating a new Person/Family History (from Home page)
     */
    public void setCreate(boolean create) {
        this.create = create;
    }

    /**
     * @return the removeRelativeId
     */
    public String getRemoveRelativeId() {
        return removeRelativeId;
    }

    /**
     * @param removeRelativeId the removeRelativeId to set
     */
    public void setRemoveRelativeId(String removeRelativeId) {
        this.removeRelativeId = removeRelativeId;
    }
}
